import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { getServerSession } from "next-auth"
import SessionProvider from "../app/components/SessionProvider"
import Navbar from "./components/Navbar"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession()
  return (
    <html lang="en">
      <body
        className={
          (inter.className, "bg-gradient-to-r from-slate-900 to-zinc-900 flex")
        }
      >
        <SessionProvider session={session}>
          <main className="w-full flex">
            <Navbar />
            <article className="w-full">{children}</article>
          </main>
        </SessionProvider>
      </body>
    </html>
  )
}
